spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ffmm?characterEncoding=utf-8
      username: root
      password: 1314
mybatis:
  mapper-locations: classpath:mappers/**.xml
  type-aliases-package: com.wz.boot.domain,com.wz.boot.vo